name: SAP BTP build and deploy CI

on:
    push:
        branches:
            main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Add cds build tooling
        run:  npm i -g @sap/cds-dk
              npm install -g mbt
              npm init -y          
              npm install -g eslint
              ls -lrt

      ##- name: Linting
      ##  shell: sh
      ##  run: npm run lint

      - name: Build
        shell: sh
        run: mbt build 